name: Test and Release

on: push

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FORCE_COLOR: 3

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Authenticate against NPM registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
      - name: Semantic release
        continue-on-error: true
        run: |
          npm i --no-save semantic-release
          npx semantic-release
      - name: Publish latest release to GitHub pages
        if: contains(github.ref, 'saga')
        run: |
          echo "machine github.com login authtoken password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          node scripts/publish-schemas.mjs
          cd gh-pages
          touch .nojekyll
          git init
          git add -A
          git commit -m 'latest release'
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
